package com.example.downsteps1.common

object AlgeriaStates {

    val all = listOf(
        AlgeriaState("All States", "كل الولايات"),
        AlgeriaState("Adrar", "أدرار"),
        AlgeriaState("Chlef", "الشلف"),
        AlgeriaState("Laghouat", "الأغواط"),
        AlgeriaState("Oum El Bouaghi", "أم البواقي"),
        AlgeriaState("Batna", "باتنة"),
        AlgeriaState("Bejaia", "بجاية"),
        AlgeriaState("Biskra", "بسكرة"),
        AlgeriaState("Bechar", "بشار"),
        AlgeriaState("Blida", "البليدة"),
        AlgeriaState("Bouira", "البويرة"),
        AlgeriaState("Tamanrasset", "تمنراست"),
        AlgeriaState("Tebessa", "تبسة"),
        AlgeriaState("Tlemcen", "تلمسان"),
        AlgeriaState("Tiaret", "تيارت"),
        AlgeriaState("Tizi Ouzou", "تيزي وزو"),
        AlgeriaState("Algiers", "الجزائر"),
        AlgeriaState("Djelfa", "الجلفة"),
        AlgeriaState("Jijel", "جيجل"),
        AlgeriaState("Setif", "سطيف"),
        AlgeriaState("Saida", "سعيدة"),
        AlgeriaState("Skikda", "سكيكدة"),
        AlgeriaState("Sidi Bel Abbes", "سيدي بلعباس"),
        AlgeriaState("Annaba", "عنابة"),
        AlgeriaState("Guelma", "قالمة"),
        AlgeriaState("Constantine", "قسنطينة"),
        AlgeriaState("Medea", "المدية"),
        AlgeriaState("Mostaganem", "مستغانم"),
        AlgeriaState("M'Sila", "المسيلة"),
        AlgeriaState("Mascara", "معسكر"),
        AlgeriaState("Ouargla", "ورقلة"),
        AlgeriaState("Oran", "وهران"),
        AlgeriaState("El Bayadh", "البيض"),
        AlgeriaState("Illizi", "إليزي"),
        AlgeriaState("Bordj Bou Arreridj", "برج بوعريريج"),
        AlgeriaState("Boumerdes", "بومرداس"),
        AlgeriaState("El Tarf", "الطارف"),
        AlgeriaState("Tindouf", "تندوف"),
        AlgeriaState("Tissemsilt", "تيسمسيلت"),
        AlgeriaState("El Oued", "الوادي"),
        AlgeriaState("Khenchela", "خنشلة"),
        AlgeriaState("Souk Ahras", "سوق أهراس"),
        AlgeriaState("Tipaza", "تيبازة"),
        AlgeriaState("Mila", "ميلة"),
        AlgeriaState("Ain Defla", "عين الدفلى"),
        AlgeriaState("Naama", "النعامة"),
        AlgeriaState("Ain Temouchent", "عين تموشنت"),
        AlgeriaState("Ghardaia", "غرداية"),
        AlgeriaState("Relizane", "غليزان"),
        AlgeriaState("Timimoun", "تيميمون"),
        AlgeriaState("Bordj Badji Mokhtar", "برج باجي مختار"),
        AlgeriaState("Ouled Djellal", "أولاد جلال"),
        AlgeriaState("Beni Abbes", "بني عباس"),
        AlgeriaState("In Salah", "عين صالح"),
        AlgeriaState("In Guezzam", "عين قزام"),
        AlgeriaState("Touggourt", "تقرت"),
        AlgeriaState("Djanet", "جانت"),
        AlgeriaState("El M'Ghair", "المغير"),
        AlgeriaState("El Meniaa", "المنيعة")
    )
}